[package]
name = "rays-rs"
version = "0.1.0"
authors = ["Sergey Grankin <sgrankin@gmail.com>"]

[dependencies]
image = "*"
log = "*"
rand = "*"
rayon = "*"
simple_logger = "*"
sdl2 = "*"
num = "*"
simdeez = "*"
tacho = "*"
hdrsample = "*"

[dependencies.cgmath]
version = "*"
features = ["swizzle"]

[profile.release]
debug = true
