[package]
name = "rays-rs"
version = "0.1.0"
authors = ["Sergey Grankin <sgrankin@gmail.com>"]
edition = '2018'

[dependencies]
cgmath = "*"
image = "*"
collision = "*"
rand = "*"
rayon = "*"
num-traits = "0.2.6"
