[package]
name = "rays-rs"
version = "0.1.0"
authors = ["Sergey Grankin <sgrankin@gmail.com>"]
edition = '2018'

[dependencies]
cgmath = "*"
image = "*"
rand = "*"
rayon = "*"
num-traits = "*"
simple_logger = "*"
log = "*"

[profile.release]
debug = true
